//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Fin_Etude___Maalem_Bin_Idik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTISAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTISAN()
        {
            this.SERVICE = new HashSet<SERVICE>();
        }
    
        public int ID_artisan { get; set; }
        public string Nom_artisan { get; set; }
        public string Prenom_artisan { get; set; }
        public System.DateTime DateN_artisan { get; set; }
        public string Genre_artisan { get; set; }
        public Nullable<int> Tele_artisan { get; set; }
        public string Email_artisan { get; set; }
        public string Mdp_artisan { get; set; }
        public Nullable<bool> Email_verifier { get; set; }
        public Nullable<bool> Artisan_Banni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE> SERVICE { get; set; }
    }
}
