//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Fin_Etude___Maalem_Bin_Idik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE_SERVICE
    {
        public int ID_commande { get; set; }
        public System.DateTime DateDePrise { get; set; }
        public int ID_service { get; set; }
        public int ID_utilisateur { get; set; }
        public Nullable<decimal> Prix_service { get; set; }
    
        public virtual SERVICE SERVICE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
