//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Fin_Etude___Maalem_Bin_Idik.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MAALEM_BIN_IDIK_DBEntities : DbContext
    {
        public MAALEM_BIN_IDIK_DBEntities()
            : base("name=MAALEM_BIN_IDIK_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UTILISATEUR> UTILISATEUR { get; set; }
        public virtual DbSet<ARTISAN> ARTISAN { get; set; }
        public virtual DbSet<METIER> METIER { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<COMMANDE_SERVICE> COMMANDE_SERVICE { get; set; }
    }
}
