//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Fin_Etude___Maalem_Bin_Idik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE()
        {
            this.COMMANDE_SERVICE = new HashSet<COMMANDE_SERVICE>();
        }
    
        public int ID_service { get; set; }
        public string Titre_service { get; set; }
        public string Description_service { get; set; }
        public int ID_metier { get; set; }
        public int ID_artisan { get; set; }
        public string Ville_service { get; set; }
    
        public virtual ARTISAN ARTISAN { get; set; }
        public virtual METIER METIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE_SERVICE> COMMANDE_SERVICE { get; set; }
    }
}
