//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Fin_Etude___Maalem_Bin_Idik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILISATEUR()
        {
            this.COMMANDE_SERVICE = new HashSet<COMMANDE_SERVICE>();
        }
    
        public int ID_utilisateur { get; set; }
        public string Nom_utilisateur { get; set; }
        public string Prenom_utilisateur { get; set; }
        public System.DateTime DateN_utilisateur { get; set; }
        public string Genre_utilisateur { get; set; }
        public Nullable<int> Tele_utilisateur { get; set; }
        public string Email_utilisateur { get; set; }
        public string Mdp_utilisateur { get; set; }
        public Nullable<bool> Email_verifier { get; set; }
        public Nullable<bool> Utilisateur_Banni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE_SERVICE> COMMANDE_SERVICE { get; set; }
    }
}
